### ISSUE TITLE
Incorrect digits output.

### ISSUE THREAD

**Issue by rsm-ltd** [davidcarver/Parallel-Chudnovsky-PI#1]
When calculating 50,000,000 digits of PI the last digit is incorrect. Like so:

    $./raspberry-pi2-openmp 50000000 1 4 > pi_50000000.txt

Output is:    0.314159...9456526546e1

Should be:  0.314159...9456526545e1

This failure occurs both on a 4 core Pi and a 2 core x86_64 PC.

Incorrect result is also verified by searching for those last digits 10 digits on http://www.angio.net/pi/

Strangely when calculating 100,000,000 digits (On a PC not a Pi) the result is correct including those digits at the 50,000,000 mark.

Edit: I notice the same error occurs when using 2 threads on a 2 core machine (as opposed to 4 threads above). Also your original code on gmp-discuss has the same problem.

**Comment by rsm-ltd** [comment]
Seem that error I reported above exists in the original gmp-chudnovsky by  Hanhong Xue when run as:

    $ ./gmp-chudnovsky 50000000 1 > pi_50000000.txt

**Comment by davidcarver** [comment]
Kari,
Thank you for the email.  I am going to take a look at the original gmp program and see if it also has the problem.  It may be that the program is generating too many digits (a few more digits than 50 Million) and the last couple of digits are wrong.  I am gratefully  that you tested the problem on another hardware architecture (Intel)  and that this is not just a problem on the arm processor.
I will let you know.

Again, thank you for trying out the program.  How did you here about about it?

Later,
David Carver

**Comment by rsm-ltd** [comment]
You got it. If I edit my out put and leaving only "14159...9456526546" then that last "6" is the 50000001 decimal place of PI. But it is wrong, should be "5". Those other digits at the end are correct.

I heard about it by reading your thread on the Pi C++ forum.

**Comment by davidcarver** [comment]
Kari,
Yep,  both programs are outputting too many digits.  In this case 19 digits.

login1.maverick(11)$ ./raspberry-pi 50000000 1 20 >50000000.txt
#terms=3525683,depth=23,threads=20,cores=20
bs         cputime = 108.270  wallclock = 21.236   factor =  5.098
div/sqrt   cputime =  9.960  wallclock =  9.895   factor =  1.007
total      cputime = 118.230  wallclock = 31.131   factor =  3.798

login1.maverick(12)$ ./raspberry-pi 50000010 1 20 >50000010.txt
#terms=3525684,depth=23,threads=20,cores=20
bs         cputime = 94.000  wallclock = 21.187   factor =  4.437
div/sqrt   cputime = 10.230  wallclock = 10.173   factor =  1.006
total      cputime = 104.230  wallclock = 31.360   factor =  3.324

login1.maverick(13)$ wc 5*txt
        2         2  50000022 50000000.txt
        2         2  50000032 50000010.txt

The last few digits for 50,000,010 digits was 94565265456452116834e1

I need to fix the program to print the correct number of digits and no more. 

Thanks,
David

**Comment by davidcarver** [comment]
Kari,
Oops, ignore the previous comment.  I was counting all the text in the file and not just the digits.
It looks like mpf_out_str is rounding the last digit by default.
But you are right, since the program is  computing "d" digits, but calls 
mpf_out_str to print "d+2" digits.  I will update the programs to call mpf_out_str to print "d" digits 
and see if I can disable rounding for mpf_str_out.

Thanks,
David

**Comment by rsm-ltd** [comment]
Great. Works here.
